// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/wangming/Documents/GitHub/flower/node_modules/.pnpm/dumi@2.4.4_@babel+core@7.24.7_@swc+helpers@0.5.1_@types+node@20.14.9_eslint@8.57.0_lightningc_hbiwfgmizq65s3eqm2c6m5lj7m/node_modules/dumi/theme-default/slots/NotFound/index.js';
