// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/wangming/Documents/GitHub/flower/node_modules/.pnpm/dumi@2.4.7_@babel+core@7.25.2_@swc+helpers@0.5.1_@types+node@22.2.0_@types+react@18.3.3_eslin_n3un4tbwir6z2wymbntggw3ude/node_modules/dumi/theme-default/slots/Tabs/index.js';
