// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import nprogress from '/Users/wangming/Documents/GitHub/flower/node_modules/.pnpm/nprogress@0.2.0/node_modules/nprogress';
import './nprogress.css';
import UserLoading from '/Users/wangming/Documents/GitHub/flower/node_modules/.pnpm/dumi@2.4.4_@babel+core@7.24.7_@swc+helpers@0.5.1_@types+node@20.14.9_eslint@8.57.0_lightningc_hbiwfgmizq65s3eqm2c6m5lj7m/node_modules/dumi/dist/client/pages/Loading';
import React, { useLayoutEffect, type FC } from 'react';
import { useSiteData } from 'dumi';

const DumiLoading: FC = () => {
  const { setLoading } = useSiteData();

  useLayoutEffect(() => {
    setLoading(true);
    nprogress.start();

    return () => {
      setLoading(false);
      nprogress.done();
    }
  }, []);

  return <UserLoading />
}

export default DumiLoading;
